/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CertificateManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admins"
      | "authorities"
      | "certificates"
      | "draftCertificate"
      | "grantAdmin"
      | "grantAuthority"
      | "revokeAdmin"
      | "revokeAuthority"
      | "revokeCertificate"
      | "signCertificate"
      | "signatures"
      | "superAdmin"
      | "verifyCertificate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateDrafted"
      | "CertificateIssued"
      | "CertificateRevoked"
      | "CertificateSigned"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admins", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "authorities",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "certificates",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "draftCertificate",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCertificate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "signCertificate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "signatures",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "superAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCertificate",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "draftCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signatures", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "superAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyCertificate",
    data: BytesLike
  ): Result;
}

export namespace CertificateDraftedEvent {
  export type InputTuple = [
    certificateHash: string,
    requiredSignatures: BigNumberish
  ];
  export type OutputTuple = [
    certificateHash: string,
    requiredSignatures: bigint
  ];
  export interface OutputObject {
    certificateHash: string;
    requiredSignatures: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [certificateHash: string];
  export type OutputTuple = [certificateHash: string];
  export interface OutputObject {
    certificateHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateRevokedEvent {
  export type InputTuple = [certificateHash: string];
  export type OutputTuple = [certificateHash: string];
  export interface OutputObject {
    certificateHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateSignedEvent {
  export type InputTuple = [certificateHash: string, authority: AddressLike];
  export type OutputTuple = [certificateHash: string, authority: string];
  export interface OutputObject {
    certificateHash: string;
    authority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [account: AddressLike, role: string];
  export type OutputTuple = [account: string, role: string];
  export interface OutputObject {
    account: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [account: AddressLike, role: string];
  export type OutputTuple = [account: string, role: string];
  export interface OutputObject {
    account: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertificateManager extends BaseContract {
  connect(runner?: ContractRunner | null): CertificateManager;
  waitForDeployment(): Promise<this>;

  interface: CertificateManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admins: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  authorities: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  certificates: TypedContractMethod<
    [arg0: string],
    [
      [bigint, bigint, bigint] & {
        status: bigint;
        requiredSignatures: bigint;
        currentSignatures: bigint;
      }
    ],
    "view"
  >;

  draftCertificate: TypedContractMethod<
    [_certificateHash: string, _requiredSignatures: BigNumberish],
    [void],
    "nonpayable"
  >;

  grantAdmin: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantAuthority: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeAdmin: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeAuthority: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeCertificate: TypedContractMethod<
    [_certificateHash: string],
    [void],
    "nonpayable"
  >;

  signCertificate: TypedContractMethod<
    [_certificateHash: string],
    [void],
    "nonpayable"
  >;

  signatures: TypedContractMethod<
    [arg0: string, arg1: AddressLike],
    [boolean],
    "view"
  >;

  superAdmin: TypedContractMethod<[], [string], "view">;

  verifyCertificate: TypedContractMethod<
    [_certificateHash: string],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "authorities"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: string],
    [
      [bigint, bigint, bigint] & {
        status: bigint;
        requiredSignatures: bigint;
        currentSignatures: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "draftCertificate"
  ): TypedContractMethod<
    [_certificateHash: string, _requiredSignatures: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantAdmin"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantAuthority"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAdmin"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAuthority"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCertificate"
  ): TypedContractMethod<[_certificateHash: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signCertificate"
  ): TypedContractMethod<[_certificateHash: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signatures"
  ): TypedContractMethod<[arg0: string, arg1: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "superAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyCertificate"
  ): TypedContractMethod<[_certificateHash: string], [bigint], "view">;

  getEvent(
    key: "CertificateDrafted"
  ): TypedContractEvent<
    CertificateDraftedEvent.InputTuple,
    CertificateDraftedEvent.OutputTuple,
    CertificateDraftedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateRevoked"
  ): TypedContractEvent<
    CertificateRevokedEvent.InputTuple,
    CertificateRevokedEvent.OutputTuple,
    CertificateRevokedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateSigned"
  ): TypedContractEvent<
    CertificateSignedEvent.InputTuple,
    CertificateSignedEvent.OutputTuple,
    CertificateSignedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "CertificateDrafted(string,uint256)": TypedContractEvent<
      CertificateDraftedEvent.InputTuple,
      CertificateDraftedEvent.OutputTuple,
      CertificateDraftedEvent.OutputObject
    >;
    CertificateDrafted: TypedContractEvent<
      CertificateDraftedEvent.InputTuple,
      CertificateDraftedEvent.OutputTuple,
      CertificateDraftedEvent.OutputObject
    >;

    "CertificateIssued(string)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;

    "CertificateRevoked(string)": TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;
    CertificateRevoked: TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;

    "CertificateSigned(string,address)": TypedContractEvent<
      CertificateSignedEvent.InputTuple,
      CertificateSignedEvent.OutputTuple,
      CertificateSignedEvent.OutputObject
    >;
    CertificateSigned: TypedContractEvent<
      CertificateSignedEvent.InputTuple,
      CertificateSignedEvent.OutputTuple,
      CertificateSignedEvent.OutputObject
    >;

    "RoleGranted(address,string)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(address,string)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
